import {Router} from "express"
import { categoryImageUpload } from "../middlewares/setDirectory"
import { upload } from "../middlewares/multerUploadImages"
import { AddColor, AddFavourite, AddProduct, AddReview, AdvancedRating, BuyNow, DeleteCategory, DeleteProductImage, DeleteTag, Delete_Product, GetReviews, NewArrivalProducts, RemoveFavourite, Search_Products, UpdateQuantity, add_product_to_cart, checkOutPayment, checkOutPayment_products, createNewCarousel, createTagAdmin, create_Category, editCategories, editTags, edit_product, filterSearch, findCartItems, findCartItemsLength, getAllCarousels, getAllCategories, getAllProducts, getAllSuggested, getAllTags_function, getDetails, getProduct, get_10_categories_admin, handleDeleteItem, removeOfSuggest, setSuggest } from "../controllers/productController"
import { checkUser, requireAdmin, requireTrader } from "../middlewares/authMiddleware"
import { uploadProduct } from "../middlewares/multerUploadingProductImages"
const router = Router()
router.get("/get-suggested" , getAllSuggested)
router.get("/new-arrival" , NewArrivalProducts)
router.get("/get-carousels" , getAllCarousels)
router.get("/search" , Search_Products)
router.get('/filter-products' , filterSearch)
router.get("/advanced-rating" , AdvancedRating)
router.get("/get-product" , getProduct)
router.post ('/check-cart-items' , checkUser , checkOutPayment_products)
router.post("/product-to-order" , checkUser , BuyNow)
router.post("/check-out-payment" , checkUser , checkOutPayment)
router.post("/add-favourite" , checkUser , AddFavourite)
router.delete("/delete-product-image" , requireAdmin , DeleteProductImage)
router.get("/get-all-review" , GetReviews)
router.delete("/remove-favourite" , checkUser , RemoveFavourite)
router.put("/update-quantity" ,checkUser , UpdateQuantity)
router.delete("/delete-item" , checkUser , handleDeleteItem)
router.get("/get-items" , checkUser , findCartItems)
router.get("/cart-items-length" , checkUser , findCartItemsLength)
router.post('/add-to-cart' , checkUser , add_product_to_cart)
router.post('/add-review' ,checkUser  , AddReview)
router.post("/create-new-product" ,requireTrader ,uploadProduct.array("images") , AddProduct)
router.post("/add-color" ,requireAdmin , uploadProduct.array("images") ,AddColor )
router.put('/edit-product' , requireAdmin , uploadProduct.array("images") , edit_product)
router.post("/create-category" ,requireAdmin ,categoryImageUpload , upload.single("image") ,create_Category )
router.get("/all-categories" , requireAdmin , getAllCategories)
router.get("/get-all-tags"  ,requireAdmin , getAllTags_function)
router.post('/create-tag' , requireAdmin ,createTagAdmin )
router.put("/edit-tag-name" , requireAdmin ,editTags )
router.put("/edit-category-name" , requireAdmin ,editCategories)
router.get("/get-categories" , requireAdmin , get_10_categories_admin)
router.delete("/delete-category" , requireAdmin , DeleteCategory)
router.delete("/delete-tag" , requireAdmin , DeleteTag)
router.delete("/delete-product" , requireAdmin , Delete_Product)
router.get("/get-details" , requireAdmin , getDetails)
router.post("/add-suggest" , requireAdmin , setSuggest)
router.delete("/remove-suggest" , requireAdmin , removeOfSuggest)
router.get("/get-all-products" , requireAdmin,getAllProducts)
router.post("/create-carousel" , requireAdmin , createNewCarousel)
export{router as productRoute}